
package webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Company", targetNamespace = "http://WebService/", wsdlLocation = "https://beep2.cellulant.com:9001/assessments/Company?WSDL")
public class Company_Service
    extends Service
{

    private final static URL COMPANY_WSDL_LOCATION;
    private final static WebServiceException COMPANY_EXCEPTION;
    private final static QName COMPANY_QNAME = new QName("http://WebService/", "Company");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://beep2.cellulant.com:9001/assessments/Company?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COMPANY_WSDL_LOCATION = url;
        COMPANY_EXCEPTION = e;
    }

    public Company_Service() {
        super(__getWsdlLocation(), COMPANY_QNAME);
    }

    public Company_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), COMPANY_QNAME, features);
    }

    public Company_Service(URL wsdlLocation) {
        super(wsdlLocation, COMPANY_QNAME);
    }

    public Company_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COMPANY_QNAME, features);
    }

    public Company_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Company_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Company
     */
    @WebEndpoint(name = "CompanyPort")
    public Company getCompanyPort() {
        return super.getPort(new QName("http://WebService/", "CompanyPort"), Company.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Company
     */
    @WebEndpoint(name = "CompanyPort")
    public Company getCompanyPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://WebService/", "CompanyPort"), Company.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COMPANY_EXCEPTION!= null) {
            throw COMPANY_EXCEPTION;
        }
        return COMPANY_WSDL_LOCATION;
    }

}
